### ISSUE TITLE
Warning for setting cell cyle duration in live cycle model to 0

### ISSUE THREAD

**Issue by johnmetzcar** [PhysiCell-Tools/PhysiCell-Studio#129]
Setting the cycle duration time to 0.0 in the live cycle model is a valid setting. However, it causes cycling to occur instantly and practically infinitely as the model has only one phase. This effectively causes the simulation execution to hang as PhysiCell makes agent after agent on the first update. 

It might be reasonable to take advantage of the Studio to warn a user that while you CAN do that, you probably don't want to.

**Comment by rheiland** [comment]
Should be in 2.27.7
