### ISSUE TITLE
Rules plots for set rules do not track updated base value

### ISSUE THREAD

**Issue by drbergman** [PhysiCell-Tools/PhysiCell-Studio#176]
As reported by a user, once a rule is set in the rules tab, the base value is fixed for plotting purposes of that rule, i.e. clicking `Plot rule` when that row is selected.

All other parameters, i.e., those defined within the Rules tab and shown in the table, do affect the plot when changed in the table.

Here's a rule with base value initially set to 1.0 when added to the table, followed by updating the base value (`migrtion bias`) to 0.5, and the rule plotted again and the base value remains at 1.0: 

### Initial base value
![image](https://github.com/PhysiCell-Tools/PhysiCell-Studio/assets/22732264/b9bb4ef2-3db3-45b0-a4ab-6fe1cc11c733)
### Initial plot
![image](https://github.com/PhysiCell-Tools/PhysiCell-Studio/assets/22732264/666f0a17-8ea1-46b4-936f-e143530b51b3)
### Update base value
![image](https://github.com/PhysiCell-Tools/PhysiCell-Studio/assets/22732264/e3e49ef5-e555-452b-8b09-83fd327d6566)
### Plot not updated even after clicking `Plot rule`
![image](https://github.com/PhysiCell-Tools/PhysiCell-Studio/assets/22732264/f410fd0b-3a72-4a2b-9de7-4ae2c5425e3a)

**Comment by rheiland** [comment]
We're getting awfully close to trying to read the user's mind. In the use case above, let's say they entered a saturation value of 0.6 (with 1.0 as original base value) and saved that into the table. Then they change the base value to 0.5. I guess we would need to check the table, see that they have a rule still with *decreasing* bias from the new 0.5 base value "down" to 0.6, and either 1) tell them it's ill-defined, please fix it or 2) automagically change the 0.6 to a new default of 0.05 (0.1 * 0.5).
I'll just do *something* I guess, then we can modify later.

**Comment by drbergman** [comment]
I think the simple solution here is grabbing the base value when the user clicks `Plot rule`.

**Comment by MathCancer** [comment]
I think keeping the “base” synced with the current cell definition is a good practice.

In principle, uers in the “rules” tab should only be editing the responses, not the base values.

Thanks!

**Comment by rheiland** [comment]
Wondering if I'm missing something obvious @drbergman . It doesn't seem that simple to me, but maybe I still don't understand rules, in general. Repeating the point I was trying to make earlier... I create rule 2 initially with a base value of 0.5. and specified it will be *increasing* with a saturation value of 1.0. Then I return to the secretion subtab and set the base value for secretion rate = 1.7. Then I return to the Rules tab, select this rule in the table, click "Plot rule" and it plots the *decreasing* (not *increasing* as stated on the rule) plot from the 1.7 down to 1.0. So, do I automatically change "increasing" to "decreasing" in the rule? Do I notify the user that there's an inconsistency and I can't read their mind? Other?

Note that running PhysiCell does not generate any warning either:
```
Adding rule for default cells:
	substrate decreases migration bias towards 0.5 with a Hill response, with half-max 20 and Hill power 4.
Adding rule for default cells:
	substrate increases substrate secretion towards 1.0 with a Hill response, with half-max 42 and Hill power 4.
Done!
```


<img width="1060" alt="Screenshot 2024-04-14 at 11 51 19 AM" src="https://github.com/PhysiCell-Tools/PhysiCell-Studio/assets/1774917/64d455a6-8961-4318-91b6-04b9b9a759dd">

**Comment by rheiland** [comment]
It feels a bit rushed, but I hope I fixed/improved this issue in the latest release:  https://github.com/PhysiCell-Tools/PhysiCell-Studio/releases/tag/v2.36.0 . I'll wait to hear from disgruntled users.

**Comment by rheiland** [comment]
The question remains whether PhysiCell should also check for a consistent "increases" or "decreases" direction in a rule (assuming I'm interpreting the situation correctly).

**Comment by rheiland** [comment]
Do we know if this issue can be closed?

**Comment by drbergman** [comment]
I think so. It looks like it worked as I played around with a couple rules, even changing the `Direction` as the base value decreased below a min value or increased above a max value
