### ISSUE TITLE
relative path for substrate .csv from ICs

### ISSUE THREAD

**Issue by rheiland** [PhysiCell-Tools/PhysiCell-Studio#267]
Perhaps we should adopt a relative path strategy, instead of absolute path, when saving/reading a substrate created via the ICs tab. For example, currently, it saves it as:
```
        <options>
            <calculate_gradients>true</calculate_gradients>
            <track_internalized_substrates_in_each_agent>true</track_internalized_substrates_in_each_agent>
            <initial_condition type="csv" enabled="true">
                <filename>/Users/heiland/git/test_barrier/barrier.csv</filename>
```
A relative path would be more consistent with cells ICs and make it easier to share models.

**Comment by drbergman** [comment]
that's very reasonable. don't remember why I used an abspath, but this makes too much sense to not do
