### ISSUE TITLE
Output folder not being saved

### ISSUE THREAD

**Issue by johnmetzcar** [PhysiCell-Tools/PhysiCell-Studio#89]
I observed that output folder not being saved to the XML, resulting in unintended overwriting of results. 

The correct target folder seems to be cleared of output, but the output goes to a previously specified folder. 

This was the latest available Studio version (did a git pull prior to starting work), using the rules option, run on a MacBook Pro 2019. Will provide more information as I uncover more specifics.

**Comment by rheiland** [comment]
Thanks! Please pull latest updates or use latest Release and see if the problem is fixed.

**Comment by johnmetzcar** [comment]
I did a git pull. This appears to be fixed. The anticipated folder was cleared and new output directed to it. I verifed the XML directly as well. Thanks!
